version: "3.0"

services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    networks:
      - network
    ports:
      - 8081:80


  app:
    build:
#      args:
#        user: user
#        uid: 1000
      context: .
      dockerfile: docker/app/Dockerfile
#    image: quizapp
#    container_name: quizApp
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - network
    depends_on:
      - database

  database:
#    container_name: mysqldb
    image: mysql:8
#    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      TZ: UTC
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 10s
      retries: 120
#s    volumes:
#      - ./docker/mysql/:/docker-entrypoint-initdb.d:ro
    networks:
      - network
    ports:
      - 33061:3306

networks:
  network:
    driver: bridge


