version: "3.0"

services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: quizApp.dockerfile
    image: quizapp
    container_name: quizApp
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - quizApp
    depends_on:
      - mysqldb
    volumes:
    - ./:/var/www

  mysqldb:
    container_name: mysqldb
    image: mysql
#    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 10s
      retries: 120
    volumes:
    - ./docker-compose/mysql/:/docker-entrypoint-initdb.d
    networks:
      - quizApp
  nginx:
    image: nginx:1.20-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
    - 8000:80
    volumes:
    - ./:/var/www
    - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - quizApp

networks:
  quizApp:
    driver: bridge


